#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AirportManagementSystem")]
	public partial class DBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserMaster(UserMaster instance);
    partial void UpdateUserMaster(UserMaster instance);
    partial void DeleteUserMaster(UserMaster instance);
    partial void InsertRoleMaster(RoleMaster instance);
    partial void UpdateRoleMaster(RoleMaster instance);
    partial void DeleteRoleMaster(RoleMaster instance);
    partial void InsertHanger_Status(Hanger_Status instance);
    partial void UpdateHanger_Status(Hanger_Status instance);
    partial void DeleteHanger_Status(Hanger_Status instance);
    partial void Insertfeedbackform(feedbackform instance);
    partial void Updatefeedbackform(feedbackform instance);
    partial void Deletefeedbackform(feedbackform instance);
    partial void InsertUser_Feedback(User_Feedback instance);
    partial void UpdateUser_Feedback(User_Feedback instance);
    partial void DeleteUser_Feedback(User_Feedback instance);
    partial void InsertPlane(Plane instance);
    partial void UpdatePlane(Plane instance);
    partial void DeletePlane(Plane instance);
    partial void InsertHanger(Hanger instance);
    partial void UpdateHanger(Hanger instance);
    partial void DeleteHanger(Hanger instance);
    partial void Inserthangerallot(hangerallot instance);
    partial void Updatehangerallot(hangerallot instance);
    partial void Deletehangerallot(hangerallot instance);
    #endregion
		
		public DBContextDataContext() : 
				base(global::DAL.Properties.Settings.Default.AirportManagementSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserMaster> UserMasters
		{
			get
			{
				return this.GetTable<UserMaster>();
			}
		}
		
		public System.Data.Linq.Table<RoleMaster> RoleMasters
		{
			get
			{
				return this.GetTable<RoleMaster>();
			}
		}
		
		public System.Data.Linq.Table<Hanger_Status> Hanger_Status
		{
			get
			{
				return this.GetTable<Hanger_Status>();
			}
		}
		
		public System.Data.Linq.Table<feedbackform> feedbackforms
		{
			get
			{
				return this.GetTable<feedbackform>();
			}
		}
		
		public System.Data.Linq.Table<User_Feedback> User_Feedbacks
		{
			get
			{
				return this.GetTable<User_Feedback>();
			}
		}
		
		public System.Data.Linq.Table<Plane> Planes
		{
			get
			{
				return this.GetTable<Plane>();
			}
		}
		
		public System.Data.Linq.Table<Hanger> Hangers
		{
			get
			{
				return this.GetTable<Hanger>();
			}
		}
		
		public System.Data.Linq.Table<hangerallot> hangerallots
		{
			get
			{
				return this.GetTable<hangerallot>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetHangerStatus")]
		public ISingleResult<GetHangerStatusResult> GetHangerStatus()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetHangerStatusResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserMaster")]
	public partial class UserMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<int> _Age;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _DoB;
		
		private string _ContactNumber;
		
		private string _AltContactNumber;
		
		private string _EMail;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _IsApprovedOn;
		
		private string _IsApprovedBy;
		
		private System.Nullable<int> _RoleId;
		
		private string _LicenseNumber;
		
		private string _AddressLine1;
		
		private string _AddressLine2;
		
		private string _City;
		
		private string _State;
		
		private string _ZipCode;
		
		private string _SSN;
		
		private EntityRef<RoleMaster> _RoleMaster;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUIDChanging(int value);
    partial void OnUIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnDoBChanging(System.Nullable<System.DateTime> value);
    partial void OnDoBChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnAltContactNumberChanging(string value);
    partial void OnAltContactNumberChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnIsApprovedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnIsApprovedOnChanged();
    partial void OnIsApprovedByChanging(string value);
    partial void OnIsApprovedByChanged();
    partial void OnRoleIdChanging(System.Nullable<int> value);
    partial void OnRoleIdChanged();
    partial void OnLicenseNumberChanging(string value);
    partial void OnLicenseNumberChanged();
    partial void OnAddressLine1Changing(string value);
    partial void OnAddressLine1Changed();
    partial void OnAddressLine2Changing(string value);
    partial void OnAddressLine2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipCodeChanging(string value);
    partial void OnZipCodeChanged();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    #endregion
		
		public UserMaster()
		{
			this._RoleMaster = default(EntityRef<RoleMaster>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoB", DbType="DateTime")]
		public System.Nullable<System.DateTime> DoB
		{
			get
			{
				return this._DoB;
			}
			set
			{
				if ((this._DoB != value))
				{
					this.OnDoBChanging(value);
					this.SendPropertyChanging();
					this._DoB = value;
					this.SendPropertyChanged("DoB");
					this.OnDoBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="VarChar(15)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltContactNumber", DbType="VarChar(15)")]
		public string AltContactNumber
		{
			get
			{
				return this._AltContactNumber;
			}
			set
			{
				if ((this._AltContactNumber != value))
				{
					this.OnAltContactNumberChanging(value);
					this.SendPropertyChanging();
					this._AltContactNumber = value;
					this.SendPropertyChanged("AltContactNumber");
					this.OnAltContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(50)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApprovedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> IsApprovedOn
		{
			get
			{
				return this._IsApprovedOn;
			}
			set
			{
				if ((this._IsApprovedOn != value))
				{
					this.OnIsApprovedOnChanging(value);
					this.SendPropertyChanging();
					this._IsApprovedOn = value;
					this.SendPropertyChanged("IsApprovedOn");
					this.OnIsApprovedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApprovedBy", DbType="VarChar(50)")]
		public string IsApprovedBy
		{
			get
			{
				return this._IsApprovedBy;
			}
			set
			{
				if ((this._IsApprovedBy != value))
				{
					this.OnIsApprovedByChanging(value);
					this.SendPropertyChanging();
					this._IsApprovedBy = value;
					this.SendPropertyChanged("IsApprovedBy");
					this.OnIsApprovedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="Int")]
		public System.Nullable<int> RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					if (this._RoleMaster.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicenseNumber", DbType="VarChar(50)")]
		public string LicenseNumber
		{
			get
			{
				return this._LicenseNumber;
			}
			set
			{
				if ((this._LicenseNumber != value))
				{
					this.OnLicenseNumberChanging(value);
					this.SendPropertyChanging();
					this._LicenseNumber = value;
					this.SendPropertyChanged("LicenseNumber");
					this.OnLicenseNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine1", DbType="VarChar(50)")]
		public string AddressLine1
		{
			get
			{
				return this._AddressLine1;
			}
			set
			{
				if ((this._AddressLine1 != value))
				{
					this.OnAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._AddressLine1 = value;
					this.SendPropertyChanged("AddressLine1");
					this.OnAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine2", DbType="VarChar(50)")]
		public string AddressLine2
		{
			get
			{
				return this._AddressLine2;
			}
			set
			{
				if ((this._AddressLine2 != value))
				{
					this.OnAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._AddressLine2 = value;
					this.SendPropertyChanged("AddressLine2");
					this.OnAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipCode", DbType="VarChar(10)")]
		public string ZipCode
		{
			get
			{
				return this._ZipCode;
			}
			set
			{
				if ((this._ZipCode != value))
				{
					this.OnZipCodeChanging(value);
					this.SendPropertyChanging();
					this._ZipCode = value;
					this.SendPropertyChanged("ZipCode");
					this.OnZipCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(10)")]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RoleMaster_UserMaster", Storage="_RoleMaster", ThisKey="RoleId", OtherKey="RoleID", IsForeignKey=true)]
		public RoleMaster RoleMaster
		{
			get
			{
				return this._RoleMaster.Entity;
			}
			set
			{
				RoleMaster previousValue = this._RoleMaster.Entity;
				if (((previousValue != value) 
							|| (this._RoleMaster.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RoleMaster.Entity = null;
						previousValue.UserMasters.Remove(this);
					}
					this._RoleMaster.Entity = value;
					if ((value != null))
					{
						value.UserMasters.Add(this);
						this._RoleId = value.RoleID;
					}
					else
					{
						this._RoleId = default(Nullable<int>);
					}
					this.SendPropertyChanged("RoleMaster");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoleMaster")]
	public partial class RoleMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private string _RoleDescription;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private string _CreaedBy;
		
		private System.Nullable<bool> _IsActive;
		
		private EntitySet<UserMaster> _UserMasters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRoleDescriptionChanging(string value);
    partial void OnRoleDescriptionChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnCreaedByChanging(string value);
    partial void OnCreaedByChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public RoleMaster()
		{
			this._UserMasters = new EntitySet<UserMaster>(new Action<UserMaster>(this.attach_UserMasters), new Action<UserMaster>(this.detach_UserMasters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleDescription", DbType="VarChar(50)")]
		public string RoleDescription
		{
			get
			{
				return this._RoleDescription;
			}
			set
			{
				if ((this._RoleDescription != value))
				{
					this.OnRoleDescriptionChanging(value);
					this.SendPropertyChanging();
					this._RoleDescription = value;
					this.SendPropertyChanged("RoleDescription");
					this.OnRoleDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreaedBy", DbType="VarChar(50)")]
		public string CreaedBy
		{
			get
			{
				return this._CreaedBy;
			}
			set
			{
				if ((this._CreaedBy != value))
				{
					this.OnCreaedByChanging(value);
					this.SendPropertyChanging();
					this._CreaedBy = value;
					this.SendPropertyChanged("CreaedBy");
					this.OnCreaedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RoleMaster_UserMaster", Storage="_UserMasters", ThisKey="RoleID", OtherKey="RoleId")]
		public EntitySet<UserMaster> UserMasters
		{
			get
			{
				return this._UserMasters;
			}
			set
			{
				this._UserMasters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserMasters(UserMaster entity)
		{
			this.SendPropertyChanging();
			entity.RoleMaster = this;
		}
		
		private void detach_UserMasters(UserMaster entity)
		{
			this.SendPropertyChanging();
			entity.RoleMaster = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hanger_Status")]
	public partial class Hanger_Status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Hangar_ID;
		
		private string _Manager_ID;
		
		private string _Status;
		
		private string _Occupancy_From_date;
		
		private string _Occupancy_till_date;
		
		private string _Available_from_date;
		
		private string _Available_till_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHangar_IDChanging(int value);
    partial void OnHangar_IDChanged();
    partial void OnManager_IDChanging(string value);
    partial void OnManager_IDChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnOccupancy_From_dateChanging(string value);
    partial void OnOccupancy_From_dateChanged();
    partial void OnOccupancy_till_dateChanging(string value);
    partial void OnOccupancy_till_dateChanged();
    partial void OnAvailable_from_dateChanging(string value);
    partial void OnAvailable_from_dateChanged();
    partial void OnAvailable_till_dateChanging(string value);
    partial void OnAvailable_till_dateChanged();
    #endregion
		
		public Hanger_Status()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hangar_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Hangar_ID
		{
			get
			{
				return this._Hangar_ID;
			}
			set
			{
				if ((this._Hangar_ID != value))
				{
					this.OnHangar_IDChanging(value);
					this.SendPropertyChanging();
					this._Hangar_ID = value;
					this.SendPropertyChanged("Hangar_ID");
					this.OnHangar_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manager_ID", DbType="VarChar(100)")]
		public string Manager_ID
		{
			get
			{
				return this._Manager_ID;
			}
			set
			{
				if ((this._Manager_ID != value))
				{
					this.OnManager_IDChanging(value);
					this.SendPropertyChanging();
					this._Manager_ID = value;
					this.SendPropertyChanged("Manager_ID");
					this.OnManager_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(2)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupancy_From_date", DbType="VarChar(10)")]
		public string Occupancy_From_date
		{
			get
			{
				return this._Occupancy_From_date;
			}
			set
			{
				if ((this._Occupancy_From_date != value))
				{
					this.OnOccupancy_From_dateChanging(value);
					this.SendPropertyChanging();
					this._Occupancy_From_date = value;
					this.SendPropertyChanged("Occupancy_From_date");
					this.OnOccupancy_From_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupancy_till_date", DbType="VarChar(10)")]
		public string Occupancy_till_date
		{
			get
			{
				return this._Occupancy_till_date;
			}
			set
			{
				if ((this._Occupancy_till_date != value))
				{
					this.OnOccupancy_till_dateChanging(value);
					this.SendPropertyChanging();
					this._Occupancy_till_date = value;
					this.SendPropertyChanged("Occupancy_till_date");
					this.OnOccupancy_till_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available_from_date", DbType="VarChar(10)")]
		public string Available_from_date
		{
			get
			{
				return this._Available_from_date;
			}
			set
			{
				if ((this._Available_from_date != value))
				{
					this.OnAvailable_from_dateChanging(value);
					this.SendPropertyChanging();
					this._Available_from_date = value;
					this.SendPropertyChanged("Available_from_date");
					this.OnAvailable_from_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available_till_date", DbType="VarChar(10)")]
		public string Available_till_date
		{
			get
			{
				return this._Available_till_date;
			}
			set
			{
				if ((this._Available_till_date != value))
				{
					this.OnAvailable_till_dateChanging(value);
					this.SendPropertyChanging();
					this._Available_till_date = value;
					this.SendPropertyChanged("Available_till_date");
					this.OnAvailable_till_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.feedbackform")]
	public partial class feedbackform : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _FFId;
		
		private string _ques1;
		
		private string _ans1;
		
		private string _ques2;
		
		private string _ans2;
		
		private string _ques3;
		
		private string _ans3;
		
		private string _ques4;
		
		private string _ans4;
		
		private string _ques5;
		
		private string _ans5;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFFIdChanging(long value);
    partial void OnFFIdChanged();
    partial void Onques1Changing(string value);
    partial void Onques1Changed();
    partial void Onans1Changing(string value);
    partial void Onans1Changed();
    partial void Onques2Changing(string value);
    partial void Onques2Changed();
    partial void Onans2Changing(string value);
    partial void Onans2Changed();
    partial void Onques3Changing(string value);
    partial void Onques3Changed();
    partial void Onans3Changing(string value);
    partial void Onans3Changed();
    partial void Onques4Changing(string value);
    partial void Onques4Changed();
    partial void Onans4Changing(string value);
    partial void Onans4Changed();
    partial void Onques5Changing(string value);
    partial void Onques5Changed();
    partial void Onans5Changing(string value);
    partial void Onans5Changed();
    #endregion
		
		public feedbackform()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FFId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long FFId
		{
			get
			{
				return this._FFId;
			}
			set
			{
				if ((this._FFId != value))
				{
					this.OnFFIdChanging(value);
					this.SendPropertyChanging();
					this._FFId = value;
					this.SendPropertyChanged("FFId");
					this.OnFFIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques1", DbType="VarChar(200)")]
		public string ques1
		{
			get
			{
				return this._ques1;
			}
			set
			{
				if ((this._ques1 != value))
				{
					this.Onques1Changing(value);
					this.SendPropertyChanging();
					this._ques1 = value;
					this.SendPropertyChanged("ques1");
					this.Onques1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ans1", DbType="VarChar(200)")]
		public string ans1
		{
			get
			{
				return this._ans1;
			}
			set
			{
				if ((this._ans1 != value))
				{
					this.Onans1Changing(value);
					this.SendPropertyChanging();
					this._ans1 = value;
					this.SendPropertyChanged("ans1");
					this.Onans1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques2", DbType="VarChar(200)")]
		public string ques2
		{
			get
			{
				return this._ques2;
			}
			set
			{
				if ((this._ques2 != value))
				{
					this.Onques2Changing(value);
					this.SendPropertyChanging();
					this._ques2 = value;
					this.SendPropertyChanged("ques2");
					this.Onques2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ans2", DbType="VarChar(200)")]
		public string ans2
		{
			get
			{
				return this._ans2;
			}
			set
			{
				if ((this._ans2 != value))
				{
					this.Onans2Changing(value);
					this.SendPropertyChanging();
					this._ans2 = value;
					this.SendPropertyChanged("ans2");
					this.Onans2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques3", DbType="VarChar(200)")]
		public string ques3
		{
			get
			{
				return this._ques3;
			}
			set
			{
				if ((this._ques3 != value))
				{
					this.Onques3Changing(value);
					this.SendPropertyChanging();
					this._ques3 = value;
					this.SendPropertyChanged("ques3");
					this.Onques3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ans3", DbType="VarChar(200)")]
		public string ans3
		{
			get
			{
				return this._ans3;
			}
			set
			{
				if ((this._ans3 != value))
				{
					this.Onans3Changing(value);
					this.SendPropertyChanging();
					this._ans3 = value;
					this.SendPropertyChanged("ans3");
					this.Onans3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques4", DbType="VarChar(200)")]
		public string ques4
		{
			get
			{
				return this._ques4;
			}
			set
			{
				if ((this._ques4 != value))
				{
					this.Onques4Changing(value);
					this.SendPropertyChanging();
					this._ques4 = value;
					this.SendPropertyChanged("ques4");
					this.Onques4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ans4", DbType="VarChar(200)")]
		public string ans4
		{
			get
			{
				return this._ans4;
			}
			set
			{
				if ((this._ans4 != value))
				{
					this.Onans4Changing(value);
					this.SendPropertyChanging();
					this._ans4 = value;
					this.SendPropertyChanged("ans4");
					this.Onans4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques5", DbType="VarChar(200)")]
		public string ques5
		{
			get
			{
				return this._ques5;
			}
			set
			{
				if ((this._ques5 != value))
				{
					this.Onques5Changing(value);
					this.SendPropertyChanging();
					this._ques5 = value;
					this.SendPropertyChanged("ques5");
					this.Onques5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ans5", DbType="VarChar(200)")]
		public string ans5
		{
			get
			{
				return this._ans5;
			}
			set
			{
				if ((this._ans5 != value))
				{
					this.Onans5Changing(value);
					this.SendPropertyChanging();
					this._ans5 = value;
					this.SendPropertyChanged("ans5");
					this.Onans5Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Feedback")]
	public partial class User_Feedback : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Fid;
		
		private string _User_ID;
		
		private System.Nullable<int> _Assessment_ID;
		
		private string _Rating_Que_1;
		
		private string _Rating_Que_2;
		
		private string _Rating_Que_3;
		
		private string _Rating_Que_4;
		
		private string _Rating_Que_5;
		
		private string _Rating_Que_6;
		
		private string _Rating_Que_7;
		
		private string _Rating_Que_8;
		
		private string _Rating_Que_9;
		
		private string _Rating_Que_10;
		
		private System.Nullable<System.DateTime> _Assessment_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFidChanging(long value);
    partial void OnFidChanged();
    partial void OnUser_IDChanging(string value);
    partial void OnUser_IDChanged();
    partial void OnAssessment_IDChanging(System.Nullable<int> value);
    partial void OnAssessment_IDChanged();
    partial void OnRating_Que_1Changing(string value);
    partial void OnRating_Que_1Changed();
    partial void OnRating_Que_2Changing(string value);
    partial void OnRating_Que_2Changed();
    partial void OnRating_Que_3Changing(string value);
    partial void OnRating_Que_3Changed();
    partial void OnRating_Que_4Changing(string value);
    partial void OnRating_Que_4Changed();
    partial void OnRating_Que_5Changing(string value);
    partial void OnRating_Que_5Changed();
    partial void OnRating_Que_6Changing(string value);
    partial void OnRating_Que_6Changed();
    partial void OnRating_Que_7Changing(string value);
    partial void OnRating_Que_7Changed();
    partial void OnRating_Que_8Changing(string value);
    partial void OnRating_Que_8Changed();
    partial void OnRating_Que_9Changing(string value);
    partial void OnRating_Que_9Changed();
    partial void OnRating_Que_10Changing(string value);
    partial void OnRating_Que_10Changed();
    partial void OnAssessment_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnAssessment_DateChanged();
    #endregion
		
		public User_Feedback()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Fid
		{
			get
			{
				return this._Fid;
			}
			set
			{
				if ((this._Fid != value))
				{
					this.OnFidChanging(value);
					this.SendPropertyChanging();
					this._Fid = value;
					this.SendPropertyChanged("Fid");
					this.OnFidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="VarChar(10)")]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assessment_ID", DbType="Int")]
		public System.Nullable<int> Assessment_ID
		{
			get
			{
				return this._Assessment_ID;
			}
			set
			{
				if ((this._Assessment_ID != value))
				{
					this.OnAssessment_IDChanging(value);
					this.SendPropertyChanging();
					this._Assessment_ID = value;
					this.SendPropertyChanged("Assessment_ID");
					this.OnAssessment_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_1", DbType="VarChar(200)")]
		public string Rating_Que_1
		{
			get
			{
				return this._Rating_Que_1;
			}
			set
			{
				if ((this._Rating_Que_1 != value))
				{
					this.OnRating_Que_1Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_1 = value;
					this.SendPropertyChanged("Rating_Que_1");
					this.OnRating_Que_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_2", DbType="VarChar(200)")]
		public string Rating_Que_2
		{
			get
			{
				return this._Rating_Que_2;
			}
			set
			{
				if ((this._Rating_Que_2 != value))
				{
					this.OnRating_Que_2Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_2 = value;
					this.SendPropertyChanged("Rating_Que_2");
					this.OnRating_Que_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_3", DbType="VarChar(200)")]
		public string Rating_Que_3
		{
			get
			{
				return this._Rating_Que_3;
			}
			set
			{
				if ((this._Rating_Que_3 != value))
				{
					this.OnRating_Que_3Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_3 = value;
					this.SendPropertyChanged("Rating_Que_3");
					this.OnRating_Que_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_4", DbType="VarChar(200)")]
		public string Rating_Que_4
		{
			get
			{
				return this._Rating_Que_4;
			}
			set
			{
				if ((this._Rating_Que_4 != value))
				{
					this.OnRating_Que_4Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_4 = value;
					this.SendPropertyChanged("Rating_Que_4");
					this.OnRating_Que_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_5", DbType="VarChar(200)")]
		public string Rating_Que_5
		{
			get
			{
				return this._Rating_Que_5;
			}
			set
			{
				if ((this._Rating_Que_5 != value))
				{
					this.OnRating_Que_5Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_5 = value;
					this.SendPropertyChanged("Rating_Que_5");
					this.OnRating_Que_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_6", DbType="VarChar(200)")]
		public string Rating_Que_6
		{
			get
			{
				return this._Rating_Que_6;
			}
			set
			{
				if ((this._Rating_Que_6 != value))
				{
					this.OnRating_Que_6Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_6 = value;
					this.SendPropertyChanged("Rating_Que_6");
					this.OnRating_Que_6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_7", DbType="VarChar(200)")]
		public string Rating_Que_7
		{
			get
			{
				return this._Rating_Que_7;
			}
			set
			{
				if ((this._Rating_Que_7 != value))
				{
					this.OnRating_Que_7Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_7 = value;
					this.SendPropertyChanged("Rating_Que_7");
					this.OnRating_Que_7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_8", DbType="VarChar(200)")]
		public string Rating_Que_8
		{
			get
			{
				return this._Rating_Que_8;
			}
			set
			{
				if ((this._Rating_Que_8 != value))
				{
					this.OnRating_Que_8Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_8 = value;
					this.SendPropertyChanged("Rating_Que_8");
					this.OnRating_Que_8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_9", DbType="VarChar(200)")]
		public string Rating_Que_9
		{
			get
			{
				return this._Rating_Que_9;
			}
			set
			{
				if ((this._Rating_Que_9 != value))
				{
					this.OnRating_Que_9Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_9 = value;
					this.SendPropertyChanged("Rating_Que_9");
					this.OnRating_Que_9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Que_10", DbType="VarChar(200)")]
		public string Rating_Que_10
		{
			get
			{
				return this._Rating_Que_10;
			}
			set
			{
				if ((this._Rating_Que_10 != value))
				{
					this.OnRating_Que_10Changing(value);
					this.SendPropertyChanging();
					this._Rating_Que_10 = value;
					this.SendPropertyChanged("Rating_Que_10");
					this.OnRating_Que_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assessment_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Assessment_Date
		{
			get
			{
				return this._Assessment_Date;
			}
			set
			{
				if ((this._Assessment_Date != value))
				{
					this.OnAssessment_DateChanging(value);
					this.SendPropertyChanging();
					this._Assessment_Date = value;
					this.SendPropertyChanged("Assessment_Date");
					this.OnAssessment_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Planes")]
	public partial class Plane : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Plane_ID;
		
		private System.Nullable<int> _Owner_ID;
		
		private string _Owner_first_Name;
		
		private string _Owner_Last_name;
		
		private System.Nullable<long> _Owner_Contact_number;
		
		private string _Owner_Email;
		
		private string _Plane_Type;
		
		private System.Nullable<short> _Plane_capacity;
		
		private EntitySet<hangerallot> _hangerallots;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPlane_IDChanging(int value);
    partial void OnPlane_IDChanged();
    partial void OnOwner_IDChanging(System.Nullable<int> value);
    partial void OnOwner_IDChanged();
    partial void OnOwner_first_NameChanging(string value);
    partial void OnOwner_first_NameChanged();
    partial void OnOwner_Last_nameChanging(string value);
    partial void OnOwner_Last_nameChanged();
    partial void OnOwner_Contact_numberChanging(System.Nullable<long> value);
    partial void OnOwner_Contact_numberChanged();
    partial void OnOwner_EmailChanging(string value);
    partial void OnOwner_EmailChanged();
    partial void OnPlane_TypeChanging(string value);
    partial void OnPlane_TypeChanged();
    partial void OnPlane_capacityChanging(System.Nullable<short> value);
    partial void OnPlane_capacityChanged();
    #endregion
		
		public Plane()
		{
			this._hangerallots = new EntitySet<hangerallot>(new Action<hangerallot>(this.attach_hangerallots), new Action<hangerallot>(this.detach_hangerallots));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plane_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Plane_ID
		{
			get
			{
				return this._Plane_ID;
			}
			set
			{
				if ((this._Plane_ID != value))
				{
					this.OnPlane_IDChanging(value);
					this.SendPropertyChanging();
					this._Plane_ID = value;
					this.SendPropertyChanged("Plane_ID");
					this.OnPlane_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_ID", DbType="Int")]
		public System.Nullable<int> Owner_ID
		{
			get
			{
				return this._Owner_ID;
			}
			set
			{
				if ((this._Owner_ID != value))
				{
					this.OnOwner_IDChanging(value);
					this.SendPropertyChanging();
					this._Owner_ID = value;
					this.SendPropertyChanged("Owner_ID");
					this.OnOwner_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_first_Name", DbType="VarChar(100)")]
		public string Owner_first_Name
		{
			get
			{
				return this._Owner_first_Name;
			}
			set
			{
				if ((this._Owner_first_Name != value))
				{
					this.OnOwner_first_NameChanging(value);
					this.SendPropertyChanging();
					this._Owner_first_Name = value;
					this.SendPropertyChanged("Owner_first_Name");
					this.OnOwner_first_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_Last_name", DbType="VarChar(100)")]
		public string Owner_Last_name
		{
			get
			{
				return this._Owner_Last_name;
			}
			set
			{
				if ((this._Owner_Last_name != value))
				{
					this.OnOwner_Last_nameChanging(value);
					this.SendPropertyChanging();
					this._Owner_Last_name = value;
					this.SendPropertyChanged("Owner_Last_name");
					this.OnOwner_Last_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_Contact_number", DbType="BigInt")]
		public System.Nullable<long> Owner_Contact_number
		{
			get
			{
				return this._Owner_Contact_number;
			}
			set
			{
				if ((this._Owner_Contact_number != value))
				{
					this.OnOwner_Contact_numberChanging(value);
					this.SendPropertyChanging();
					this._Owner_Contact_number = value;
					this.SendPropertyChanged("Owner_Contact_number");
					this.OnOwner_Contact_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_Email", DbType="VarChar(100)")]
		public string Owner_Email
		{
			get
			{
				return this._Owner_Email;
			}
			set
			{
				if ((this._Owner_Email != value))
				{
					this.OnOwner_EmailChanging(value);
					this.SendPropertyChanging();
					this._Owner_Email = value;
					this.SendPropertyChanged("Owner_Email");
					this.OnOwner_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plane_Type", DbType="VarChar(10)")]
		public string Plane_Type
		{
			get
			{
				return this._Plane_Type;
			}
			set
			{
				if ((this._Plane_Type != value))
				{
					this.OnPlane_TypeChanging(value);
					this.SendPropertyChanging();
					this._Plane_Type = value;
					this.SendPropertyChanged("Plane_Type");
					this.OnPlane_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plane_capacity", DbType="SmallInt")]
		public System.Nullable<short> Plane_capacity
		{
			get
			{
				return this._Plane_capacity;
			}
			set
			{
				if ((this._Plane_capacity != value))
				{
					this.OnPlane_capacityChanging(value);
					this.SendPropertyChanging();
					this._Plane_capacity = value;
					this.SendPropertyChanged("Plane_capacity");
					this.OnPlane_capacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Plane_hangerallot", Storage="_hangerallots", ThisKey="Plane_ID", OtherKey="planeid")]
		public EntitySet<hangerallot> hangerallots
		{
			get
			{
				return this._hangerallots;
			}
			set
			{
				this._hangerallots.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hangerallots(hangerallot entity)
		{
			this.SendPropertyChanging();
			entity.Plane = this;
		}
		
		private void detach_hangerallots(hangerallot entity)
		{
			this.SendPropertyChanging();
			entity.Plane = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hanger")]
	public partial class Hanger : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Hanger_ID;
		
		private string _Manager_ID;
		
		private string _Manager_Address_Line_1;
		
		private string _Manager_Address_Line_2;
		
		private string _City;
		
		private string _State;
		
		private System.Nullable<long> _Zip_Code;
		
		private EntitySet<hangerallot> _hangerallots;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHanger_IDChanging(int value);
    partial void OnHanger_IDChanged();
    partial void OnManager_IDChanging(string value);
    partial void OnManager_IDChanged();
    partial void OnManager_Address_Line_1Changing(string value);
    partial void OnManager_Address_Line_1Changed();
    partial void OnManager_Address_Line_2Changing(string value);
    partial void OnManager_Address_Line_2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZip_CodeChanging(System.Nullable<long> value);
    partial void OnZip_CodeChanged();
    #endregion
		
		public Hanger()
		{
			this._hangerallots = new EntitySet<hangerallot>(new Action<hangerallot>(this.attach_hangerallots), new Action<hangerallot>(this.detach_hangerallots));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hanger_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Hanger_ID
		{
			get
			{
				return this._Hanger_ID;
			}
			set
			{
				if ((this._Hanger_ID != value))
				{
					this.OnHanger_IDChanging(value);
					this.SendPropertyChanging();
					this._Hanger_ID = value;
					this.SendPropertyChanged("Hanger_ID");
					this.OnHanger_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manager_ID", DbType="VarChar(100)")]
		public string Manager_ID
		{
			get
			{
				return this._Manager_ID;
			}
			set
			{
				if ((this._Manager_ID != value))
				{
					this.OnManager_IDChanging(value);
					this.SendPropertyChanging();
					this._Manager_ID = value;
					this.SendPropertyChanged("Manager_ID");
					this.OnManager_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manager_Address_Line_1", DbType="VarChar(100)")]
		public string Manager_Address_Line_1
		{
			get
			{
				return this._Manager_Address_Line_1;
			}
			set
			{
				if ((this._Manager_Address_Line_1 != value))
				{
					this.OnManager_Address_Line_1Changing(value);
					this.SendPropertyChanging();
					this._Manager_Address_Line_1 = value;
					this.SendPropertyChanged("Manager_Address_Line_1");
					this.OnManager_Address_Line_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manager_Address_Line_2", DbType="VarChar(100)")]
		public string Manager_Address_Line_2
		{
			get
			{
				return this._Manager_Address_Line_2;
			}
			set
			{
				if ((this._Manager_Address_Line_2 != value))
				{
					this.OnManager_Address_Line_2Changing(value);
					this.SendPropertyChanging();
					this._Manager_Address_Line_2 = value;
					this.SendPropertyChanged("Manager_Address_Line_2");
					this.OnManager_Address_Line_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip_Code", DbType="BigInt")]
		public System.Nullable<long> Zip_Code
		{
			get
			{
				return this._Zip_Code;
			}
			set
			{
				if ((this._Zip_Code != value))
				{
					this.OnZip_CodeChanging(value);
					this.SendPropertyChanging();
					this._Zip_Code = value;
					this.SendPropertyChanged("Zip_Code");
					this.OnZip_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanger_hangerallot", Storage="_hangerallots", ThisKey="Hanger_ID", OtherKey="hangid")]
		public EntitySet<hangerallot> hangerallots
		{
			get
			{
				return this._hangerallots;
			}
			set
			{
				this._hangerallots.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hangerallots(hangerallot entity)
		{
			this.SendPropertyChanging();
			entity.Hanger = this;
		}
		
		private void detach_hangerallots(hangerallot entity)
		{
			this.SendPropertyChanging();
			entity.Hanger = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hangerallot")]
	public partial class hangerallot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AID;
		
		private string _allotdetails;
		
		private System.Nullable<int> _hangid;
		
		private System.Nullable<int> _planeid;
		
		private System.Nullable<bool> _status;
		
		private EntityRef<Hanger> _Hanger;
		
		private EntityRef<Plane> _Plane;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAIDChanging(long value);
    partial void OnAIDChanged();
    partial void OnallotdetailsChanging(string value);
    partial void OnallotdetailsChanged();
    partial void OnhangidChanging(System.Nullable<int> value);
    partial void OnhangidChanged();
    partial void OnplaneidChanging(System.Nullable<int> value);
    partial void OnplaneidChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    #endregion
		
		public hangerallot()
		{
			this._Hanger = default(EntityRef<Hanger>);
			this._Plane = default(EntityRef<Plane>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long AID
		{
			get
			{
				return this._AID;
			}
			set
			{
				if ((this._AID != value))
				{
					this.OnAIDChanging(value);
					this.SendPropertyChanging();
					this._AID = value;
					this.SendPropertyChanged("AID");
					this.OnAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allotdetails", DbType="VarChar(50)")]
		public string allotdetails
		{
			get
			{
				return this._allotdetails;
			}
			set
			{
				if ((this._allotdetails != value))
				{
					this.OnallotdetailsChanging(value);
					this.SendPropertyChanging();
					this._allotdetails = value;
					this.SendPropertyChanged("allotdetails");
					this.OnallotdetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hangid", DbType="Int")]
		public System.Nullable<int> hangid
		{
			get
			{
				return this._hangid;
			}
			set
			{
				if ((this._hangid != value))
				{
					if (this._Hanger.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhangidChanging(value);
					this.SendPropertyChanging();
					this._hangid = value;
					this.SendPropertyChanged("hangid");
					this.OnhangidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planeid", DbType="Int")]
		public System.Nullable<int> planeid
		{
			get
			{
				return this._planeid;
			}
			set
			{
				if ((this._planeid != value))
				{
					if (this._Plane.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnplaneidChanging(value);
					this.SendPropertyChanging();
					this._planeid = value;
					this.SendPropertyChanged("planeid");
					this.OnplaneidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hanger_hangerallot", Storage="_Hanger", ThisKey="hangid", OtherKey="Hanger_ID", IsForeignKey=true)]
		public Hanger Hanger
		{
			get
			{
				return this._Hanger.Entity;
			}
			set
			{
				Hanger previousValue = this._Hanger.Entity;
				if (((previousValue != value) 
							|| (this._Hanger.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hanger.Entity = null;
						previousValue.hangerallots.Remove(this);
					}
					this._Hanger.Entity = value;
					if ((value != null))
					{
						value.hangerallots.Add(this);
						this._hangid = value.Hanger_ID;
					}
					else
					{
						this._hangid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hanger");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Plane_hangerallot", Storage="_Plane", ThisKey="planeid", OtherKey="Plane_ID", IsForeignKey=true)]
		public Plane Plane
		{
			get
			{
				return this._Plane.Entity;
			}
			set
			{
				Plane previousValue = this._Plane.Entity;
				if (((previousValue != value) 
							|| (this._Plane.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Plane.Entity = null;
						previousValue.hangerallots.Remove(this);
					}
					this._Plane.Entity = value;
					if ((value != null))
					{
						value.hangerallots.Add(this);
						this._planeid = value.Plane_ID;
					}
					else
					{
						this._planeid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Plane");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetHangerStatusResult
	{
		
		private int _Hanger_ID;
		
		private string _Manager_ID;
		
		private string _City;
		
		private string _State;
		
		private System.Nullable<long> _Zip_Code;
		
		private string _Status;
		
		public GetHangerStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hanger_ID", DbType="Int NOT NULL")]
		public int Hanger_ID
		{
			get
			{
				return this._Hanger_ID;
			}
			set
			{
				if ((this._Hanger_ID != value))
				{
					this._Hanger_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manager_ID", DbType="VarChar(100)")]
		public string Manager_ID
		{
			get
			{
				return this._Manager_ID;
			}
			set
			{
				if ((this._Manager_ID != value))
				{
					this._Manager_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip_Code", DbType="BigInt")]
		public System.Nullable<long> Zip_Code
		{
			get
			{
				return this._Zip_Code;
			}
			set
			{
				if ((this._Zip_Code != value))
				{
					this._Zip_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
